"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from . import lcmt_densetact_measurement


class lcmt_densetact_measurement_data(object):
    __slots__ = ["numSensors", "sensorData"]

    __typenames__ = ["int8_t", "lcmt_densetact_measurement"]

    __dimensions__ = [None, ["numSensors"]]

    def __init__(self):
        self.numSensors = 0
        self.sensorData = []

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_densetact_measurement_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.numSensors))
        for i0 in range(self.numSensors):
            assert (
                self.sensorData[i0]._get_packed_fingerprint()
                == lcmt_densetact_measurement._get_packed_fingerprint()
            )
            self.sensorData[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_densetact_measurement_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_densetact_measurement_data._decode_one(buf)

    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_densetact_measurement_data()
        self.numSensors = struct.unpack(">b", buf.read(1))[0]
        self.sensorData = []
        for i0 in range(self.numSensors):
            self.sensorData.append(lcmt_densetact_measurement._decode_one(buf))
        return self

    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_densetact_measurement_data in parents:
            return 0
        newparents = parents + [lcmt_densetact_measurement_data]
        tmphash = (
            0x5EB95EA8BC9C69BF
            + lcmt_densetact_measurement._get_hash_recursive(newparents)
        ) & 0xFFFFFFFFFFFFFFFF
        tmphash = (
            ((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)
        ) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_densetact_measurement_data._packed_fingerprint is None:
            lcmt_densetact_measurement_data._packed_fingerprint = struct.pack(
                ">Q", lcmt_densetact_measurement_data._get_hash_recursive([])
            )
        return lcmt_densetact_measurement_data._packed_fingerprint

    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(
            ">Q", lcmt_densetact_measurement_data._get_packed_fingerprint()
        )[0]
