"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct


class lcmt_fingertips_position(object):
    __slots__ = ["utime", "curPos", "curVel", "curQuat"]

    __typenames__ = ["int64_t", "double", "double", "double"]

    __dimensions__ = [None, [9], [9], [12]]

    def __init__(self):
        self.utime = 0
        self.curPos = [0.0 for dim0 in range(9)]
        self.curVel = [0.0 for dim0 in range(9)]
        self.curQuat = [0.0 for dim0 in range(12)]

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_fingertips_position._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack(">9d", *self.curPos[:9]))
        buf.write(struct.pack(">9d", *self.curVel[:9]))
        buf.write(struct.pack(">12d", *self.curQuat[:12]))

    def decode(data):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_fingertips_position._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_fingertips_position._decode_one(buf)

    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_fingertips_position()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.curPos = struct.unpack(">9d", buf.read(72))
        self.curVel = struct.unpack(">9d", buf.read(72))
        self.curQuat = struct.unpack(">12d", buf.read(96))
        return self

    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_fingertips_position in parents:
            return 0
        tmphash = (0xFDD623E28803B4E2) & 0xFFFFFFFFFFFFFFFF
        tmphash = (
            ((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)
        ) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_fingertips_position._packed_fingerprint is None:
            lcmt_fingertips_position._packed_fingerprint = struct.pack(
                ">Q", lcmt_fingertips_position._get_hash_recursive([])
            )
        return lcmt_fingertips_position._packed_fingerprint

    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_fingertips_position._get_packed_fingerprint())[
            0
        ]
