"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct


class lcmt_fingertips_target_kinematics(object):
    __slots__ = ["utime", "isAbsoluteTargetPos", "targetPos", "targetVel"]

    __typenames__ = ["int64_t", "boolean", "double", "double"]

    __dimensions__ = [None, None, [9], [9]]

    def __init__(self):
        self.utime = 0
        self.isAbsoluteTargetPos = False
        self.targetPos = [0.0 for dim0 in range(9)]
        self.targetVel = [0.0 for dim0 in range(9)]

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_fingertips_target_kinematics._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.utime, self.isAbsoluteTargetPos))
        buf.write(struct.pack(">9d", *self.targetPos[:9]))
        buf.write(struct.pack(">9d", *self.targetVel[:9]))

    def decode(data):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_fingertips_target_kinematics._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_fingertips_target_kinematics._decode_one(buf)

    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_fingertips_target_kinematics()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.isAbsoluteTargetPos = bool(struct.unpack("b", buf.read(1))[0])
        self.targetPos = struct.unpack(">9d", buf.read(72))
        self.targetVel = struct.unpack(">9d", buf.read(72))
        return self

    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_fingertips_target_kinematics in parents:
            return 0
        tmphash = (0x6D15E77D3ED039AE) & 0xFFFFFFFFFFFFFFFF
        tmphash = (
            ((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)
        ) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_fingertips_target_kinematics._packed_fingerprint is None:
            lcmt_fingertips_target_kinematics._packed_fingerprint = struct.pack(
                ">Q", lcmt_fingertips_target_kinematics._get_hash_recursive([])
            )
        return lcmt_fingertips_target_kinematics._packed_fingerprint

    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(
            ">Q", lcmt_fingertips_target_kinematics._get_packed_fingerprint()
        )[0]
