"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_frame_visual(object):

    __slots__ = ["frame"]

    __typenames__ = ["double"]

    __dimensions__ = [[4, 4]]

    def __init__(self):
        self.frame = [ [ 0.0 for dim1 in range(4) ] for dim0 in range(4) ]
        """ LCM Type: double[4][4] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_frame_visual._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(4):
            buf.write(struct.pack('>4d', *self.frame[i0][:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_frame_visual._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_frame_visual._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_frame_visual()
        self.frame = []
        for i0 in range(4):
            self.frame.append(struct.unpack('>4d', buf.read(32)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_frame_visual in parents: return 0
        tmphash = (0x7799665928848f92) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_frame_visual._packed_fingerprint is None:
            lcmt_frame_visual._packed_fingerprint = struct.pack(">Q", lcmt_frame_visual._get_hash_recursive([]))
        return lcmt_frame_visual._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_frame_visual._get_packed_fingerprint())[0]

