name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: mshalm 
  GITHUB_REPOSITORY: DAIRLab/dair_pll
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: python:3.9

    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          apt-get install -y rsync
          apt-get install -y cmake
          apt-get install -y libeigen3-dev
          ls
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          git clone "https://token:${GITHUB_TOKEN}@github.com/libigl/eigen" ./Eigen
        shell: bash
      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "docs/buildsite.sh"
        shell: bash
