name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: mshalm 
  GITHUB_REPOSITORY: DAIRLab/dair_pll
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with: 
          python-version: '3.9'
          architecture: 'x64'
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "docs/buildsite.sh"
        shell: bash
